name: fetch-nhl-playoff-stats
run-name: ${{ github.actor }} is fetching NHL data
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 20-23,0-8 * * *"
jobs:
  fetch-nhl-player-playoff-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update stats.json
        run: |
          cd .github/workflows
          if node fetch-player-playoff-stats.mjs
          then
            git config --global user.name 'player-stats-fetcher'
            git config --global user.email 'lehtu@users.noreply.github.com'
            git add .
            git commit -am "Update player playoff stats in stats.json"
            git push
          else
            echo "nothing to update"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
